### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by wtzb** [wtzb/SalienProgress#3]
TODO features to add to SalienProgress:
- [ ]  ETA
- [ ]  Progress bar
- [x]  Sort current active planets by progress (high to low) instead of activation time - Done, thanks @dimitarnestorov !
- [ ]  Responsiveness
- [x]  Show amount of zones (hard, medium, easy) left on active planets - Done, https://github.com/wtzb/SalienProgress/commit/208a82dc8cd198f9dcf23ffdc9f3bec3a8d98d76
- [ ] Implement lazy loading to save bandwidth
